# Generated by Django 3.2.16 on 2022-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=40)),
                ('task_duration', models.DurationField()),
                ('task_status', models.IntegerField(default=0)),
                ('task_priority', models.IntegerField(default=3)),
            ],
        ),
    ]
